### PR TITLE
add d-captainkenya

### PR DESCRIPTION
**Pull request by D-C4ptain**

### CODE REVIEW

**Review by castorichy — COMMENTED** [review]
steps followed ready to be merged

**Comment by D-C4ptain** [comment]
Whats up here?

**Review by yrncollo — APPROVED** [review]

**Comment by yrncollo** [comment]
Sorry for the late response but thanks for contributing to the organisation. You can now find some projects we collaborate together as a team.

**Comment by D-C4ptain** [comment]
Cool.

**Pull request merged**
